#!/usr/bin/env python3
"""UserPromptSubmit: Codex-only gate toggle commands.

This hook does not auto-start tasks from ordinary prompts. The gate is normally
off and is turned on by the Codex skill or by explicit `fable gate on` /
`forge on` commands. That keeps the hard gate scoped to deliberate use.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import read_payload, project_root, run_gate, session_id  # noqa: E402

# `forge <on|off|status>` optionally scoped: session (this chat) | project (this dir) |
# machine (whole desktop). Handled by the hook, never sent to the model.
SCOPE_SYNONYMS = {
    "session": "session", "here": "session", "this": "session", "chat": "session", "s": "session",
    "project": "project", "dir": "project", "repo": "project", "folder": "project", "p": "project",
    "machine": "machine", "all": "machine", "desktop": "machine", "global": "machine",
    "everywhere": "machine", "m": "machine",
}
# Match the whole `forge <verb> ...` prefix so ANY toggle-intent prompt is HANDLED here
# (never leaked to the model), even with junk trailing args — those become an invalid
# message, not a silent fall-through into a real task.
# re.S so a multi-line prompt that still STARTS `forge <verb> ...` is captured here and
# handled (blocked as invalid), never falling through and leaking to the model.
_TOGGLE_RE = re.compile(
    r"^/?(?:forge|fable(?:\s+gate)?|mythos(?:\s+gate)?|페이블(?:\s+게이트)?|미토스(?:\s+게이트)?|falbe-yeon-codex)[:\s]+"
    r"(on|off|status|stop|start)\b\s*(.*)$",
    re.I | re.S,
)


def _parse_toggle(prompt: str):
    """-> (verb in {on,off,status,invalid}, scope) or None (not a toggle prompt)."""
    low = prompt.strip().lower()
    if low in ("forge?", "/forge?", "fable gate?", "/fable gate?", "mythos gate?",
               "/mythos gate?", "페이블?", "/페이블?", "페이블 게이트?", "/페이블 게이트?",
               "미토스?", "/미토스?", "미토스 게이트?", "/미토스 게이트?"):
        return ("status", "project")
    m = _TOGGLE_RE.match(low)
    if not m:
        return None
    verb = {"stop": "off", "start": "on"}.get(m.group(1), m.group(1))
    rest = m.group(2).strip()
    if not rest:
        return (verb, "project")            # bare `forge off` -> this dir
    if rest in SCOPE_SYNONYMS:
        return (verb, SCOPE_SYNONYMS[rest])  # `forge off here|all|...`
    return ("invalid", rest)                 # `forge off please now` -> handled, not leaked

# Fallback only — normally the exact, grade-specific contract is generated by the gate
# (forge_gate.py `contract`) so the model gets every pass-condition up front and writes a
# first-try-passing spec, instead of discovering each rule by getting blocked (each such
# round burns a turn + re-reads the growing context). Single source of truth = no drift.
NOTICE_FALLBACK = (
    "[fable-forge] A gated task is active. Write .forge/spec.json COMPLETELY in one edit "
    "(restated_goal that differs from the ask, non_goals, must_read with real paths, >=2 "
    "rejected_alternatives, risks, constraints.invariant, runnable acceptance_criteria), "
    "self-check with the spec gate, then implement. Edits are blocked until it passes. "
    "Toggle off by typing 'forge off'. Do not narrate this to the user."
)


def emit_context(text: str) -> None:
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "UserPromptSubmit", "additionalContext": text}}))


def emit_block(reason: str) -> None:
    print(json.dumps({"decision": "block", "reason": reason}))


def main() -> int:
    if os.environ.get("FORGE_BYPASS") == "1":
        return 0
    payload = read_payload()
    root = project_root(payload)
    prompt = (payload.get("prompt", "") or "").strip()
    sid = session_id(payload)

    # in-session toggle — handled here, never reaches the model
    tg = _parse_toggle(prompt)
    if tg:
        verb, scope = tg
        if verb == "invalid":
            emit_block(f"fable-forge: unknown scope '{scope}'. Use none/project (this dir), "
                       "here (this chat), or all (whole machine).")
            return 0
        if verb == "status":
            raw = run_gate("state", "--root", root, "--sid", sid, "--verbose")[1].strip()
            runtime = run_gate("runtime-state", "--root", root, "--sid", sid, "--verbose")[1].strip()
            emit_block("fable-forge: " + raw + " | " + runtime)
            return 0
        if scope == "session" and not sid:
            emit_block("fable-forge: no session id available here — use 'forge "
                       f"{verb} project' (this dir) or 'forge {verb} all' (whole machine).")
            return 0
        run_gate("toggle", "--root", root, "--scope", scope, "--set", verb, "--sid", sid)
        emit_block(f"fable-forge: gate {verb.upper()} [{scope}]. "
                   + run_gate("state", "--root", root, "--sid", sid, "--verbose")[1].strip()
                   + " | "
                   + run_gate("runtime-state", "--root", root, "--sid", sid, "--verbose")[1].strip())
        return 0

    # Deliberately no work-shaped auto-start. The skill starts the gate with the
    # bundled codex_fable_gate.py helper so ordinary Codex tasks remain untouched.
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception as exc:
        sys.stderr.write(f"fable-forge user_prompt_submit error (failing open): {exc}\n")
        raise SystemExit(0)
